name: BlockyClaim
main: com.blockycraft.blockyclaim.BlockyClaim
version: 1.0
author: Bernardo Zukerman
description: Plugin de protecao de terreno com economia baseada em ferro.
softdepend: [BlockyFactions, BlockyGeoIP]

permissions:
  blockyclaim.*:
    description: Da acesso a todos os comandos do BlockyClaim.
    default: op
  blockyclaim.claim:
    description: Permite o uso do comando /claim e seus subcomandos.
    default: true
  blockyclaim.trust:
    description: Permite o uso do comando /trust.
    default: true
  blockyclaim.untrust:
    description: Permite o uso do comando /untrust.
    default: true

commands:
  claim:
    description: Compra e gerencia blocos de protecao.
    usage: /claim <comprar|saldo|confirm>
    permission: blockyclaim.claim
  trust:
    description: Concede permissao a um jogador em seu terreno.
    usage: /trust <jogador>
    permission: blockyclaim.trust
    aliases: [confiar]
  untrust:
    description: Remove a permissao de um jogador em seu terreno.
    usage: /untrust <jogador>
    permission: blockyclaim.untrust
    aliases: [negarconfianca, desconfiar]