name: BlockyClaim
main: com.blockycraft.blockyclaim.BlockyClaim
version: 1.0 # Versao atualizada conforme sua indicacao
author: Bernardo Zukerman
description: Plugin de protecao de terrenos estilo GriefPrevention adaptado para Beta 1.7.3.

softdepend:
  - BlockyFactions

commands:
  claim:
    description: Gerencia seus terrenos protegidos (claims).
    aliases: [terreno]
    usage: |
      /claim saldo - Mostra seus blocos de protecao.
      /claim comprar <qtde> - Compra blocos de protecao.
      /claim confirm <nome> - Confirma a criacao de um claim.
      /claim list [jogador] - Lista seus claims ou de outro jogador.
      /claim sell <preco> - Coloca o claim atual a venda.
      /claim adquirir <novo-nome> - Compra um claim que esta a venda.
      /claim unsell - Cancela a venda do claim atual.
      /claim ocupar <novo-nome> - Ocupa um claim abandonado.
  trust:
    description: Da permissao a um jogador no claim onde voce esta.
    usage: /trust <jogador>
  untrust:
    description: Remove a permissao de um jogador no claim onde voce esta.
    usage: /untrust <jogador>

permissions:
  blockyclaim.user:
    description: Permissoes basicas para usar o sistema de claims.
    default: true
    children:
      blockyclaim.claim: true
      blockyclaim.trust: true
      blockyclaim.untrust: true
      blockyclaim.list.self: true

  blockyclaim.admin:
    description: Permissoes administrativas para o BlockyClaim.
    default: op
    children:
      blockyclaim.user: true
      blockyclaim.list.other: true # Permite /claim list <outro_jogador>
      # Adicionar futuras permissoes de admin aqui (ex: blockyclaim.reload)

  # Permissoes individuais (para maior controle)
  blockyclaim.claim:
    description: Permite usar todos os subcomandos do /claim (saldo, comprar, confirm, sell, etc.).
    default: true
  blockyclaim.trust:
    description: Permite usar /trust.
    default: true
  blockyclaim.untrust:
    description: Permite usar /untrust.
    default: true
  blockyclaim.list.self:
    description: Permite usar /claim list (para si mesmo).
    default: true
  blockyclaim.list.other:
    description: Permite usar /claim list [outro_jogador].
    default: op